[package]
name = "test_helpers"
version= "4.0.0-beta.1"
authors = ["Brushfam <varex.silver@727.ventures>"]
edition = "2021"

[lib]
name = "test_helpers"
path = "lib.rs"

[profile.dev]
codegen-units = 16
